/**
 * This files is essentially --> <html> + <head> + layout 
 */
import { Montserrat, Walter_Turncoat } from 'next/font/google';
import './globals.css';

import Navbar from '@/app/components/Navbar';
import Footer from '@/app/components/Footer';

/**
 * ===========================
 *          FONTS
 * ===========================
 */
const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800"],
  variable: '--font-montserrat',
});

const walter = Walter_Turncoat({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-walter',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * ===========================
 *          LAYOUT
 * ===========================
 * Layout - wrapper around all pages 
 * Children is where the page appears 
 * Folders control routing, it is looking for the page.jsx files for contents
 */
export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${montserrat.variable} ${walter.variable}`}>

        <Navbar />

        {children}

        <Footer />
      </body>
    </html>
  );
}
